### ISSUE TITLE
Phone number restrictions

### ISSUE THREAD

**Issue by chilio** [Bottelet/DaybydayCRM#126]
Hey, 
global countries wise, there shouldn't be phone validation with max 10 chars.
Accepted format should cover `+phone number` with at least 12 chars.
Without it you should not use `tel:` in `a href="...`
I would suggest using one of available libraries for validation, like for example (laravel-phone)...
Finally phone numbers do not have to be 255 long in database....

**Comment by jhuebel** [comment]
I'm in the middle of moving, so this won't be implemented until at least
late-September. But it is on my to-do list. Phone number validation,
city/state/country lookup and several other contact related improvements
are planned.

The move to separate contact records was implemented in as simple of a way
as possible when 1.2 was released. The intention was to come back to it and
improve it later.

I'm thinking these improvements will be included in 2.0, which will also
move Flarepoint to Laravel 6, Bootstrap 4 and officially support PHP 7.3.

**Comment by Bottelet** [comment]
If these are still a problem in Version 2.0.0
https://github.com/Bottelet/DaybydayCRM/releases/tag/2.0.0

Please reopen with new information
