### ISSUE TITLE
Issues when installing dependencies: composer version 1.10.8

### ISSUE THREAD

**Issue by vitorfleite** [Bottelet/DaybydayCRM#148]
Deprecation Notice: Class Tests\Unit\Controllers\Client\AbsenceControllerTest located in C:/Users/Vitor/Desktop/DaybydayCRM-develop/tests\Unit\Controllers\Absence\AbsenceControllerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

Deprecation Notice: Class Tests\Unit\Controllers\Client\AppointmentsControllerTest located in C:/Users/Vitor/Desktop/DaybydayCRM-develop/tests\Unit\Controllers\Appointment\AppointmentsControllerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

Deprecation Notice: Class Tests\Unit\Controllers\Project\PaymentsControllerAddPaymentTest located in C:/Users/Vitor/Desktop/DaybydayCRM-develop/tests\Unit\Controllers\Payment\PaymentsControllerAddPaymentTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

Deprecation Notice: Class Tests\Unit\Controllers\Project\PaymentsControllerTest located in C:/Users/Vitor/Desktop/DaybydayCRM-develop/tests\Unit\Controllers\Payment\PaymentsControllerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

Deprecation Notice: Class Tests\Unit\Controllers\Client\UsersControllerCalendarTest located in C:/Users/Vitor/Desktop/DaybydayCRM-develop/tests\Unit\Controllers\User\UsersControllerCalendarTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

Deprecation Notice: Class Tests\Unit\Deadline\GetDateFormatTest located in C:/Users/Vitor/Desktop/DaybydayCRM-develop/tests\Unit\Format\GetDateFormatTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

Deprecation Notice: Class Tests\Unit\Invoice\PaymentSourceEnumTest located in C:/Users/Vitor/Desktop/DaybydayCRM-develop/tests\Unit\Payment\PaymentSourceEnumTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in C:/Users/Vitor/Desktop/DaybydayCRM-develop/vendor/ezyang/htmlpurifier/library\HTMLPurifier\Language\classes\en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by Bottelet** [comment]
Hmmm Interesting, I do not get this error, when does it happen?

**Comment by Bottelet** [comment]
https://github.com/Bottelet/DaybydayCRM/commit/6f495a623148a27067a911b6af3eb0d3ea9227b6
It should be fixed on develop... Please let me know if you still have trouble.
