### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by mohamed-alashry** [Bottelet/DaybydayCRM#149]
the scripts not working correctly due to missing jQuery

![Capture](https://user-images.githubusercontent.com/16100373/86044606-98ac5b00-ba4a-11ea-877a-2ea9c3514590.PNG)

**Comment by Bottelet** [comment]
Have you done `npm install` and maybe `npm run dev`?

**Comment by vitorfleite** [comment]
After done it showed a new error. The buttons are not collapsing.

![newbug](https://user-images.githubusercontent.com/7070675/86053013-3c3b4280-ba2e-11ea-9bec-ea8d18cc789f.jpeg)

**Comment by mohamed-alashry** [comment]
now collapse in sidebar not opening
![Capture](https://user-images.githubusercontent.com/16100373/86157762-25691e80-bb08-11ea-9355-b97cc9acec01.PNG)

**Comment by vitorfleite** [comment]
Mohamed, 
In vendor.js change:
    if (!data && options.toggle && /show|hide/.test(option)) options.toggle = false
to:
      if (!data && options.toggle && /show|hide/.test(options)) options.toggle = false
