### ISSUE TITLE
Is this application compatible with Laravel7?

### ISSUE THREAD

**Issue by ASonawane** [Bottelet/DaybydayCRM#151]
Will this application work with Laravel 7 (latest stable release) of Laravel? And what are the steps to achieve the compatibility?

Are their any plans of upgrading it to Laravel 7 in near future?

**Comment by Bottelet** [comment]
It is not yet, but it is definitely on the backlog, the only really thing there is to do is follow Laravels official upgrade guide 
https://laravel.com/docs/7.x/upgrade

**Comment by Bottelet** [comment]
I've created an issue.
https://github.com/Bottelet/DaybydayCRM/issues/152
