### ISSUE TITLE
Upgrade to Laravel 7

### ISSUE THREAD

**Issue by Bottelet** [Bottelet/DaybydayCRM#152]

**Comment by nielsdrost7** [comment]
If you want to upgrade to Laravel take a look at for example the permissions package.
Entrust is ...well.. dead, but its successor is Laratrust.
There is no database changes needed, you just need to interchange entrust with laratrust (and then start testing)

I haven't looked at the other packages yet

**Comment by Bottelet** [comment]
Thanks for the tip! Yeah, I've been thinking about getting rid of Entrust, because it's not updated anymore, the way I have solved it for now though is to put it inside its own folder structure.Thanks for the tip, will give Laratrust and look

**Comment by Bottelet** [comment]
https://github.com/Bottelet/DaybydayCRM/commit/9ff214bbfd63937aad5f458fcf065868067bfdb4
Very simple upgrade.
