### ISSUE TITLE
Default documentation about installation - not working

### ISSUE THREAD

**Issue by PovilasKorop** [Bottelet/DaybydayCRM#153]
Hey Casper,
Wanted to review DaybydayCRM on my Youtube channel, as you pointed me on Twitter, but I can't recommend to my audience a project that fails on installation.

1. On `composer install`, there's a warning: "_Deprecation warning: Your package name bottelet/DaybydayCRM is invalid, it should not contain uppercase characters. We suggest using bottelet/daybyday-crm instead. Make sure you fix this as Composer 2.0 will error._" Not sure if you want to fix it, but for the future, I would think you should.
2. On seeding dummy data, according to this - https://github.com/Bottelet/DaybydayCRM/wiki/Insertion-of-dummy-data - there's no such class as `DummyDatabaseSeeder`, there are separate classes like `ClientsDummyTableSeeder` - so should I run all of them separately, or did you plan to create one Dummy class at some point, combining all of them?
3. On viewing the Clients table, I got a lot of browser console errors: 
<img width="1440" alt="Screen Shot 2020-07-07 at 10 16 18 AM" src="https://user-images.githubusercontent.com/1510147/86735653-9d20d700-c03b-11ea-9e9a-9915e4ac9a49.png"> - so I thought I would probably need to compile the JavaScript. After running `npm install` and `npm run dev`, the errors disappeared and it's all working now, but it was never mentioned in any documentation.

Let me know if/when you fix those issues, so I would get back to the plan of the review.

**Comment by Bottelet** [comment]
Hi @PovilasKorop 

You are right, sorry, and that gives a bad impression of the CRM.

All the above errors have been fixed, and the documentation updated. Cheers for pointing it out.

**Comment by Bottelet** [comment]
If you are running into any other problems please let me know, and I'll look into it.

**Comment by PovilasKorop** [comment]
@Bottelet yeah found a few more "show-stoppers" that prevent the review from happening, created issues for them. Nice work on fixing them quickly!
