### ISSUE TITLE
Many duplicated DB queries for the settings

### ISSUE THREAD

**Issue by PovilasKorop** [Bottelet/DaybydayCRM#156]
Not a serious bug, but just caught while looking at a Debugbar. On any page you're calling the settings multiple times, maybe cache them somewhere or put into some View Composer globally?

<img width="1440" alt="Screen Shot 2020-07-08 at 8 30 24 AM" src="https://user-images.githubusercontent.com/1510147/86880601-9787c780-c0f5-11ea-97fe-20910d974fdb.png">

**Comment by Bottelet** [comment]
I fixed it with a cache here:
https://github.com/Bottelet/DaybydayCRM/commit/8f24d401f1f3d5343223c1723b989a0a6117b798

Cheers, gonna wait merge to master till the sidebar problem is fixed.
