### ISSUE TITLE
Target class [Spatie\Cors\Cors] not exist

### ISSUE THREAD

**Issue by tongvanduc** [Bottelet/DaybydayCRM#157]
![image](https://i.ibb.co/YyW3JJG/image.png)

**Comment by tongvanduc** [comment]
You need to add the spatie/laravel-cors package to composer.json

**Comment by Bottelet** [comment]
This should fix it:
https://github.com/Bottelet/DaybydayCRM/commit/b030185f59d78c9f252a37142f08a3efe1edc589
Cors are actually not used for anything, on the open-source version so there should be no reason to have it.
