### ISSUE TITLE
Side Nav Bar Menu Not working with docker install

### ISSUE THREAD

**Issue by Rohrig** [Bottelet/DaybydayCRM#160]
Using the docker install Readme the sidebar menus don't open. The routes work fine, just a collapse issue i assume.

**Comment by Bottelet** [comment]
@Rohrig Have you done Npm install and npm run dev?

**Comment by Rohrig** [comment]
yes, I followed the Readme instructions exactly

**Comment by Rohrig** [comment]
@Bottelet I made a short video of the install process so you can see the issue. I'll try to find a solution but I'm not very familiar with the project so no promises. 

https://youtu.be/QqWapWWiAkI

**Comment by Bottelet** [comment]
Hmm yeah okay I see, can you try deleting your node_modules folder? and do npm install and npm run dev again?

**Comment by Rohrig** [comment]
@Bottelet Thanks. That did it.

It should, in theory, work the first time around. Do you know what the issue may be?

**Comment by Bottelet** [comment]
Hmm, @Rohrig I agree it definitely should, I am not sure, maybe something went wrong in the installation. Dunno, sorry, but glad it worked.

**Comment by vitorfleite** [comment]
@Rohrig send us a picture with the google chrome's console after pressed the side nav bar menu.
