### ISSUE TITLE
 Cannot convert object to primitive value

### ISSUE THREAD

**Issue by isaacabensur** [Bottelet/DaybydayCRM#168]
I have a problem when i try with a click in menu item parent. In the console fo crhome appears

 Cannot convert object to primitive value

![image](https://user-images.githubusercontent.com/3707691/88489706-80e9c900-cf5b-11ea-80f5-ee0ffb885d05.png)

![image](https://user-images.githubusercontent.com/3707691/88489685-63b4fa80-cf5b-11ea-94d6-aa5cfa6e0d0c.png)

**Comment by canerksk** [comment]
I have this problem too and I still can't solve it.

**Comment by ricardoperovano** [comment]
same error here

**Comment by canerksk** [comment]
When I remove public/js/vendor.js line 732 code, the problem seems correct, but I don't know where another line is connected.

delete this line;


`if (!data && options.toggle && /show|hide/.test(option)) options.toggle = false`

**Comment by ricardoperovano** [comment]
I solved upgrading jquery to 3.5.1

**Comment by isaacabensur** [comment]
Thanks!!! Is solved now!!!
