### ISSUE TITLE
Cannot find VerifyController

### ISSUE THREAD

**Issue by peeyushx** [Bottelet/DaybydayCRM#173]
couldn't understand what's the issue but the nav menu items that have dropdown are not working, when rendered route to a herf link, the error comes: 
In Container.php line 806:
Target class [App\Http\Controllers\VerifyController] does not exist.
Spent hours trying to solve it but couldn't

**Comment by peeyushx** [comment]
using laravel 7

**Comment by Bottelet** [comment]
@peeyushx Where do you experience this problem?

**Comment by Bottelet** [comment]
And did this commit fix it, maybe?
https://github.com/Bottelet/DaybydayCRM/commit/e4f0bbad799bec422c81725562253db39544ee92

**Comment by rm-yakovenko** [comment]
> the nav menu items that have dropdown are not working

This one seems related to #165

**Comment by Edgarborras94** [comment]
Have you updated your jquery or bootstrap version?

I needed to change a id in `/resources/views/layouts/master.blade.php`: line 38

From:
```php
...
<nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas-sm" role="navigation">
...
```

To:
```php
...
<nav id="MainMenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas-sm" role="navigation">
...
```

Hope it helps
