### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by Abhay-8019** [Bottelet/DaybydayCRM#178]
im runing this crm  on local system   localhost/daybyday/public      but its not running 

when i was runing this on php artisan command its runing why
 help me

**Comment by Edgarborras94** [comment]
Did you follow all the instructions from the [Installation page](https://github.com/Bottelet/DaybydayCRM/wiki/Install) ?

Just tried to fresh install and no problem on my side.

**Comment by Bottelet** [comment]
@Abhay-8019 Did you fix the problem?

**Comment by Abhay-8019** [comment]
yes   now its working 
thnx
