### ISSUE TITLE
Ownership / Restriction of Clients by User / Organisation

### ISSUE THREAD

**Issue by MCKLtech** [Bottelet/DaybydayCRM#190]
We have a use case whereby certain users would only have access to certain clients. For example:

Organisation EU: User A, User B, User C

Organisation USA : User D, User E, User F

Organisation EU, and its users, can only see clients of the Organisation EU. 

Organisation USA, and its users, can only see clients of the Organisation USA. 

Is there a way to achieve this without setting up independent instances or tenants? Could Users and Clients be part of an Organisation 'role' that would only permit them to interact with those models in the same role?

**Comment by Bottelet** [comment]
This can not be done out of the box today. You would be able to add it yourself without too much hassle easily, I believe. Another way to achieve this would be to basically host two different CRM systems, one for the US and one for the EU. And then they would only have access to their own corresponding data.

**Comment by MCKLtech** [comment]
@Bottelet , thank you for the response. I was hoping to avoid a completely separate install scenario.

Do you have any pointer as to how this could be set up at a code level? Are roles a good idea here or is there a more extensive / better option?

**Comment by Bottelet** [comment]
I think you can do this by adding a new organization table and having a reference to the users, tasks, etc. or trying to do it with departments, which would mean that you can't use departments for what they are meant to though. You could also do it with roles probably, but no matter what you do you will have to change the data structure.

The better option would be to go to https://daybydaycrm.com and sign up with two different accounts, and then your problem would be solved ;)
