### ISSUE TITLE
Class 'Memcached' not found

### ISSUE THREAD

**Issue by bradashfaq** [Bottelet/DaybydayCRM#191]
Class 'Memcached' not found is coming. Any idea what should we do ?

**Comment by MCKLtech** [comment]
Came here to open this same issue. I'm guessing it is to do with an adapter.

 ```
Class 'Memcached' not found

  at vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php:69
    65|      * @return \Memcached
    66|      */
    67|     protected function createMemcachedInstance($connectionId)
    68|     {
  > 69|         return empty($connectionId) ? new Memcached : new Memcached($connectionId);
    70|     }
    71| 
    72|     /**
    73|      * Set the SASL credentials on the Memcached connection.

  • A class import is missing: You have a missing class import. Try importing this class: `League\Flysystem\Cached\Storage\Memcached`. 
```

**Comment by Bottelet** [comment]
When does this happened? What are you trying to do? I usually use redis.

tor. 15. okt. 2020 21.24 skrev MCKLtech <notifications@github.com>:

**Comment by MCKLtech** [comment]
The fix is in my first comment. In cache.php the driver is set to memcache which will cause an error for actions in composer or artisan. The fix is to change this to the correct driver for the landscape or if running locally, change it to 'file'

**Comment by bradashfaq** [comment]
Thanks, It is fixed by cache.php I have changed the drivers and now working :)

**Comment by Nirys** [comment]
Generally an issue when you don't have memcached PHP extension installed/enabled.  Suggest using file caching driver as repo default - have raised a PR.

@Bottelet ... any chance you'd mark this repo for Hacktoberfest? :)

**Comment by Bottelet** [comment]
@Nirys I am not actually sure what "Hacktoberfest" is about, and what is required, but it sounds like something I could consider.

**Comment by Nirys** [comment]
Thanks @Bottelet .  Hacktoberfest is an annual event that encourages people to contribute to open source projects through meaningful PRs.

Projects can opt in by adding the topic "hacktoberfest", or can allow individual PRs to count by labeling the PR with hacktoberfest-accepted

**Comment by Bottelet** [comment]
Fixed https://github.com/Bottelet/DaybydayCRM/pull/192 Thanks @Nirys
