### ISSUE TITLE
Note for MariaDB (e.g. Plesk users)

### ISSUE THREAD

**Issue by thistehneisen** [Bottelet/DaybydayCRM#195]
```./migrations/2016_05_21_205532_create_activities_table.php:23:            $table->json('properties')->nullable();```
Has to be changed to $table->text for MariaDB versions < 10.2 (e.g. Server version: 10.1.44-MariaDB-0ubuntu0.18.04.1)

**Comment by thistehneisen** [comment]
Will add also here further:
```found 623 vulnerabilities (613 low, 2 moderate, 8 high)``` doesn't look to good (`npm install`) and is there a reason why Company name can't be changed from Media to anything else?

**Comment by Bottelet** [comment]
This can be done, in the DB or tinker, if you wish. It's a symptom from the hosted solution sorry! Might make a fix for this.
