### ISSUE TITLE
Google Drive Integration

### ISSUE THREAD

**Issue by dymond** [Bottelet/DaybydayCRM#197]
Are there any instructions on how to set this up? The button in settings does not work and I've added credentials into `config/services.php` to no avail. I've googled trying to find anything about this, but it doesn't seem like there is much documentation out there.

**Comment by Bottelet** [comment]
Hi @dymond The GDrive Google Integration is not 100% available on the open-source project yet. Is this something you need, or can you handle it with local storage?
