### ISSUE TITLE
An error occurs when posting an avatar image at users create or update

### ISSUE THREAD

**Issue by kazuyoshi-tech** [Bottelet/DaybydayCRM#200]
The error is as follows when uploading the avatar image as written in the title

![スクリーンショット 2020-11-15 16 30 37](https://user-images.githubusercontent.com/55447682/99179342-0807ba80-2760-11eb-90ef-1a658f150ae6.png)

![スクリーンショット 2020-11-15 15 25 09](https://user-images.githubusercontent.com/55447682/99178773-fc18fa00-2759-11eb-882b-877eca544465.png)

![スクリーンショット 2020-11-15 15 25 18](https://user-images.githubusercontent.com/55447682/99178780-03400800-275a-11eb-8a3a-f3d8ca10d4fb.png)

![スクリーンショット 2020-11-15 15 25 36](https://user-images.githubusercontent.com/55447682/99178782-04713500-275a-11eb-9e9a-15b13f3f5298.png)

When I checked the source code, this variable was null
```
dd($settings->toArray(), $settings->external_id);
$path = Storage::put($settings->external_id, $file);
```
![スクリーンショット 2020-11-15 15 21 58](https://user-images.githubusercontent.com/55447682/99179031-e953f480-275c-11eb-8c1d-cb203c4167ab.png)

I think the intended function is to upload an image to the file path described below.
```
storage/Auth(user)->external_id/filename
```

If you can tell me the file path of the avatar image to upload, will I fix it?
thanks!!

**Comment by kazuyoshi-tech** [comment]
I'm sorry

It seems to be a function to upload images to AWS-S3

I had a misunderstanding

**Comment by TuanAnh266** [comment]
Hi, i have the same problem, but i store image in public disk not AWS-S3 but why i still got that error, please help :D
