### ISSUE TITLE
Force a new status on invoice?

### ISSUE THREAD

**Issue by lYesterdaYl** [Bottelet/DaybydayCRM#201]
I can't register a payment before sending an invoice, but I see it says I can force a new status on invoice. How do I do that?

**Comment by Bottelet** [comment]
Hi @lYesterdaYl I am not sure i know what you mean, where does it say you can force a status on an invoice?

**Comment by lYesterdaYl** [comment]
Sorry, I made some arrangement later, but here is the sentence.
![image](https://user-images.githubusercontent.com/5135163/100781891-826f4600-33c0-11eb-80af-a2ebb1fe1a81.png)

**Comment by Bottelet** [comment]
Should be possible be clicking the "send invoice" button on the right side, inside the invoice page.
