### ISSUE TITLE
Issue creating / migrating dummy database in Azure Web-App

### ISSUE THREAD

**Issue by rodent-x** [Bottelet/DaybydayCRM#204]
Hi

First - many thanks for the CRM!

I have followed the installation steps in the documentation to install the application on an Azure Web Application with MySQL 'In App'.

I have created an empty database but when trying to run 'php artisan migrate' I get the following error:

D:\home\site\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:70
      PDOException::("SQLSTATE[HY000] [2002] An attempt was made to access a socket in a way forbidden by its access permissions.

I can access the database using phpMyAdmin and have no issue there.
Any idea if there is something special with the way an Azure web-app has to be treated?

Thanks in advance for any help

Denis McFadden

**Comment by Bottelet** [comment]
Hi Denis,

I'm sorry I do not have a lot of Azure experience, maybe try by starting to get a normal Laravel application running, and then move on to daybydayCRM?
