### ISSUE TITLE
The profile image stored under storage/app instead of storage/public

### ISSUE THREAD

**Issue by lYesterdaYl** [Bottelet/DaybydayCRM#214]
Hi, the profile image file should be stored under storage/public in order to display with image tag. right?

**Comment by lYesterdaYl** [comment]
Hi, can anyone help? I already change the storage setting in filesystem.php to 'local'. I tried to upload an avatar. I do see the image store in the storage, but the image is broken in the system.

**Comment by rm-yakovenko** [comment]
Hello @lYesterdaYl .

Could you try to add `public` disk https://github.com/laravel/laravel/blob/7.x/config/filesystems.php#L50-L57 and use it as default?

Don't forget to run `php artisan storage:link`.

Regards.

**Comment by lYesterdaYl** [comment]
Hi,
Sorry for the delay, I have problem on running `php artisan storage:link`. When I run it, it prompt this error
```
In Filesystem.php line 265:

  symlink(): No such file or directory
```

I had this error before, but it was caused by not deleting the storage file in the public dir. I checked the folder, but there is no storage folder. Can you help me on this?

**Comment by rm-yakovenko** [comment]
Okay, I think I got the problem.

Could you try the following code:

```bash
mv storage/app/public storage/app/public.old
mkdir storage/app/public
php artisan storage:link
```


There is no `storage/app/public` folder in the code that's why `php artisan storage:link` creates an invalid symlink.

**Comment by lYesterdaYl** [comment]
> Okay, I think I got the problem.
> 
> Could you try the following code:
> 
> ```shell
> mv storage/app/public storage/app/public.old
> mkdir storage/app/public
> php artisan storage:link
> ```
> 
> There is no `storage/app/public` folder in the code that's why `php artisan storage:link` creates an invalid symlink.

Hi, I just found there a file in the storage/app name "public". I think that's why storage:link wasn't working. And the public setting makes it works too. Thanks.
