### ISSUE TITLE
New Installation but Left Navigation Not Clickable

### ISSUE THREAD

**Issue by jerry-lee-2020** [Bottelet/DaybydayCRM#226]
Dear Contributors,
I am new to this CRM and I am having trouble setting this up.  After installing the application I can login with the default admin account, but none of the links on the left navigation pane is clickable. Is there something obvious that I am missing to get this fixed?

Please advise. Thank you.

**Comment by Bottelet** [comment]
Hi, @jerry-lee-2020,

You have to run ỳarn install && yarn dev`
