### ISSUE TITLE
question: Is it multi-tenancy system?

### ISSUE THREAD

**Issue by sprklinginfo** [Bottelet/DaybydayCRM#230]
Hello, I am looking for a CRM built by Laravel, ideally, I hope to find a package for an existing laravel application but failed. Then I come across this project which looks nice. A great project! but I am wondering if the system can be used as a multi-tenancy solution? So each user can manage his/her own small team with its own clients? Thank you in advance!

**Comment by Bottelet** [comment]
It is possible, but it is not out of the box, as the license does not allow for reselling. If you want each user to be able to handle their own small team, I suggest you try and look at departments, it could most likely be done with this.
