### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by ceciogit** [Bottelet/DaybydayCRM#231]
Hello Guys, as title say this is not an issue, ive tried writing @Bottelet on twitter (i have registred on twitter only for this .. lol) or find some discord channel of yours without success. please feel free to delete this if you think is totally the wrong place and sorry for that!

I am actually "porting" a Cms/Cck (content construction kit) that i have created and used for years for multiple purposes ex. simple cms for website up to micro-ERP/CRM for small business companies.
the software is currently written in php 7.4 and is based on the Joomla! Framework.
it contains the logic for the creation of Models Views and Controllers php files directly from the backend through a "drag and drop" interface that generates a json which in turn is used for the creation of the MySql tables and the UI.
I am quite proud of my software and it still allows me to save a lot of time if the customer asks to add a couple of fields, or relationships, even if the fields are galleries, file uploaders , etc.

However I am trying to migrate everything to Laravel + Sanctum + Vue + Axios + TailwindCss and going in SPA
i usually work in the dark and totally alone "like a worm"  but ive thinked that would be nice to have and give some help... sharing the project with someone who is interested in making something similar, and then ive found DayByDayCRM .. and i like it a lot . if you are interested in porting this to the Dependencies i have mentioned above let me know. (also if you want make it happen in something different then DayByDayCRM.. i mean new project...).

Let me know @ my discord Cecio#6850 
Thank you guys and sorry again for placing this directly on GitHub Issues. 

Peace and Cheers

**Comment by Bottelet** [comment]
Contacted you on Twitter.
