### ISSUE TITLE
notification mark as read error

### ISSUE THREAD

**Issue by redx1t** [Bottelet/DaybydayCRM#236]
Call to a member function markAsRead() on null 

error on clicking on the notifications section. missing the notifications model and am unable to locate the markasread as well as unreadnotifications model extension.

**Comment by Bottelet** [comment]
Will look into this. Thanks!

**Comment by Bottelet** [comment]
Hello, @redx1t I can not reproduce this, can you give me some more information?

**Comment by redx1t** [comment]
Let me look at it and get you a step by step process of reproduction by 24th Apr 2021

**Comment by redx1t** [comment]
I have reviewed a fresh installation and seem not to be able to reproduce this error. Also, noticed on the installation guide the git link is to flarepoint-crm.git instead of daybyday.git. I am not sure whether or not that is on purpose. Check and correct if it is. I will keep on the platform and IF i am able to reproduce the bug, re open this issue. Thank you :)
