### ISSUE TITLE
External_id error running migration

### ISSUE THREAD

**Issue by kobeumut** [Bottelet/DaybydayCRM#239]
if I want to install with PostgreSQL, I got a blow error;
```SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "external_id" violates not-null constraint
DETAIL:  Failing row contains (1, null, payment-create, Add payment, Be able to add a new payment on a invoice, payment, 2021-04-01 13:13:37, 2021-04-01 13:13:37). (SQL: insert into "permissions" ("display_name", "name", "description", "grouping", "updated_at", "created_at") values (Add payment, payment-create, Be able to add a new payment on a invoice, payment, 2021-04-01 13:13:37, 2021-04-01 13:13:37) returning "id")
```
<img width="1228" alt="Screen Shot 2021-04-01 at 14 12 08" src="https://user-images.githubusercontent.com/5182289/113310803-48cc2e80-9311-11eb-907f-cc7e8161976b.png">

I think it's related to #186. Also I have succeeded to install it with MySQL. I've tried to change the nullable field for external_id in the migration folder but I've got another error with pgsql. You should definitely look into this problem, I actually wanted to use it with pgsql.

**Comment by Bottelet** [comment]
I haven't tried using Daybyday with a PostgreSQL database. I might try and get onto that at some point, but not for now, I'll gladly merge a PR if you find a fix. Else currently only MySQL is supported.
