### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by ranjit-git** [Bottelet/DaybydayCRM#247]
i got bellow error during installation 

user@user-xx:~/Desktop/huntr/DaybydayCRM$  php artisan migrate --seed

   Illuminate\Database\QueryException 

  could not find driver (SQL: select * from information_schema.tables where table_schema = daybyday and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675| 

      +34 vendor frames 
  35  artisan:30
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by Bottelet** [comment]
Hi, @ranjit-git  does the DB exists?
