### ISSUE TITLE
Error command php artisan key:generate

### ISSUE THREAD

**Issue by Basilou38** [Bottelet/DaybydayCRM#262]
Hi @Bottelet 

I would like to try your CRM, but I cannot install it, I have an error with this command : 

`php artisan key:generate`

![Sans titre](https://user-images.githubusercontent.com/31843047/122903861-19e1b980-d350-11eb-8a9d-309b920135f2.png)

**Comment by zakariaarrid** [comment]
hi @Basilou38 

Make sure your .env file exist already

**Comment by Basilou38** [comment]
@zakariaarrid
I do not understand.

Here are the files / folder installed
![Capture](https://user-images.githubusercontent.com/31843047/123992917-4d65b900-d9cc-11eb-86c9-5117508c3c1c.JPG)

What to do ?

**Comment by Basilou38** [comment]
ok I understand, you have to create the .env file and copy / paste the code from the .env.example file.

the following command to work => php artisan key:generate
but I have a "command not found" error with this command =>  npm install

Sorry, i'm starting ;-)

**Comment by Basilou38** [comment]
why the "npm install" command does not work ? @zakariaarrid
