### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by ugintl** [Bottelet/DaybydayCRM#271]
On the install instructions, I see `git clone https://github.com/Bottelet/Flarepoint-crm.git` whereas the repo has a url `git clone https://github.com/Bottelet/DaybydayCRM.git` Is it a mistake?

**Comment by spham** [comment]
good luck install and documentions is not well documented

**Comment by Bottelet** [comment]
Hi @ugintl 

Yes this seems to be a mistake, that is the old repo, I will fix this. 

@spham I'm sorry if the documentation for the free version isn't enough to help you get started, many people have had success with the current documentation. Let me know if I can help you with anything. Or else feel free to make a PR to update the documentation.
