### ISSUE TITLE
Fatal error: require(): Failed opening required '/var/www/html/public/../vendor/autoload.php'

### ISSUE THREAD

**Issue by hktalent** [Bottelet/DaybydayCRM#284]
docker-compose up -d
[http](http://127.0.0.1/index.php)

Warning: require(/var/www/html/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/public/index.php on line 20

Fatal error: require(): Failed opening required '/var/www/html/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/index.php on line 20

**Comment by hktalent** [comment]
https://github.com/Bottelet/DaybydayCRM/wiki/Install-using-Docker
docker-compose exec php composer install
docker-compose exec php php artisan migrate --seed
docker-compose exec php npm install
docker-compose exec php npm run dev

**Comment by hktalent** [comment]
Illuminate\Database\QueryException
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select * from `users` where `email` = admin@admin.com and `users`.`deleted_at` is null limit 1)
http://127.0.0.1/index.php/login

**Comment by rm-yakovenko** [comment]
Hello @hktalent!

Could you try to set `DB_HOST=db` in https://github.com/Bottelet/DaybydayCRM/blob/master/docker-compose.env#L6 ?

**Comment by hktalent** [comment]
@rm-yakovenko thanks
